version : "2.2"
services:

  eureka-service:
     build: ".\\Eureka"
     image: eureka
     ports:
       - "8761:8761"
  mysqldb:
     image: mysql:5.7
     restart: unless-stopped
     environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=project
     ports:
       - "8050:3306"
  zuul-gateway:
     build: ".\\zull"
     image: zuul-gateway
     environment:
       - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
     ports:
       - "2222:2222"
     depends_on:
       - eureka-service
  crm-microservice:
     build: ".\\crmmicroservice"
     image: crm-microservice
     environment:
       - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
     ports:
       - "3000:3000"
     depends_on:
       - eureka-service
  rh-microservice:
       build: ".\\Ressourceshumaines"
       image: rh-microservice
       environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
       ports:
        - "3001:3001"
       depends_on:
        -eureka-service
  project:
    depends_on:
      - mysqldb
    build: ".\\project"
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/project?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "eureka.client.serviceUrl.defaultZone": "http://eureka-service:8761/eureka/",
        "eureka.client.register-with-eureka" : "true",
        "spring.application.name" : "Project"

      }'
  Flask-service:
     build: ".\\FlaskApi"
     image: flask
     environment:
       - EUREKA_SERVICE_URL=http://eureka-service:8761/eureka/
     ports:
       - "5000:5000"
     depends_on:
       - eureka-service

   project-management-ms :
     build: ".\\project-management"
     image: project-management
     environment:
       - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
     ports:
       - "8080:8080"
     depends_on:
       -eureka-service
  mongo:
     image: mongo
     volumes:
       - ./database:/data
     ports:
       - "27017:27017"

volumes:
  db:
