server:
  port: 2222
spring:
  cloud:
    gateway:
      routes:
      - id: crm-microservice
        uri: http://crm-microservice:3000/
        predicates:
        - Path=/template/spring/**
      - id: Flask-service
        uri: http://Flask-service:5000/
        predicates:
        - Path=/template/flask
