version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=project
    ports:
      - 8050:3306
  springeurekaserver:
    build: ../springeurekaserver
    image: springeurekaserver
    restart: unless-stopped
    ports:
      - 8761:8761
  gateway:
    build: ../gateway
    depends_on:
      - project
      - eurekaclient
    image: gateway
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      eureka.client.serviceUrl.defaultZone: http://springeurekaserver:8761/eureka  
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://project:8082
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: project
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /SpringMVC/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://eurekaclient:8090
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: eurekaclient
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /warehouse/**
  eurekaclient:
    depends_on:
      - mysqldb
    build: ../eurekaclient
    restart: on-failure
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/warehouse?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.hibernate.ddl-auto" : "create",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "eureka.client.serviceUrl.defaultZone": "http://springeurekaserver:8761/eureka/",
        "eureka.client.register-with-eureka" : "true",
        "spring.application.name" : "Warehouse"
        
      }'
  project:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/project?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "eureka.client.serviceUrl.defaultZone": "http://springeurekaserver:8761/eureka/",
        "eureka.client.register-with-eureka" : "true",
        "spring.application.name" : "Project"
        
      }'
      
    

volumes:
  db: